[project]
name = "tiangong-lca-spec"
version = "0.1.0"
description = "Structured orchestration pipeline for Tiangong LCA spec coding."
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27",
    "pydantic>=2.6",
    "pydantic-settings>=2.1",
    "tenacity>=8.2",
    "structlog>=24.1",
    "langchain-core>=0.1.35",
    "langgraph>=0.1.9",
    "python-dotenv>=1.0",
]

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.uv.sources]
tiangong-lca-spec = { path = "src" }

[tool.uv.workspace]
members = ["."]

[tool.hatch.build.targets.wheel]
packages = ["src/tiangong_lca_spec"]

[tool.hatch.build.targets.sdist]
include = ["src/tiangong_lca_spec", "README.md", "pyproject.toml"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
