# Example secrets configuration for Tiangong LCA spec coding workflow.
# Copy to .secrets/secrets.toml and replace placeholder values with real credentials.

[OPENAI]
API_KEY = "<YOUR_OPENAI_API_KEY>"
MODEL = "gpt-4.1"

[LANGSMITH]
API_KEY = "<YOUR_LANGSMITH_API_KEY>"
PROJECT = "Tiangong LCA Spec Workflow"
ENDPOINT = "https://api.smith.langchain.com"
TRACING_V2 = true
CALLBACKS_BACKGROUND = true
SESSION = "tiangong-lca-dev"
TAGS = ["tiangong", "spec-coding"]
METADATA = { environment = "local" }

[TianGong_LCA_Remote]
transport = "streamable_http"
service_name = "TianGong_LCA_Remote"
url = "https://lcamcp.tiangong.earth/mcp"
api_key = "<YOUR_TG_LCA_REMOTE_API_KEY>"

[tidas_data_validate]
transport = "streamable_http"
service_name = "Tidas_Data_Validate"
tool_name = "Tidas_Data_Validate_Tool"
url = "http://192.168.1.140:9278/mcp"
api_key = "<YOUR_TIDAS_API_KEY_OR_EMPTY>"
